feat: implented notification preference UI for cadence
openedx/frontend-app-account pull request #1013
Opened 2024-03-11 12:34 UTC by ayesha-waris

[INF-1227](https://2u-internal.atlassian.net/browse/INF-1277)
**Description:**

We now will have a new email setting related to email cadences.
Options for email cadence for a notification can be Daily, Weekly and Immediately.
Complete UI as shown in [mockup](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=2072-8529&mode=design&t=2oADgBEXGpGyVx5L-0)

Complete integration with BE to successfully update these email cadence settings

2024-03-18 19:39 UTC, awais-ansari requested changes

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +    <Collapsible.Advanced open={appToggle} data-testid={`${appId}-app`} className={classNames({ 'mb-5': appToggle })}>
why is there a need to add conditional class?

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +  }, [appId]);
It is not a good way to add verticle alignment. over complex

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +                <div className="border-left h-100 vertical-line" />
Positioning and margin can help to achieve this.

2024-03-18 19:39 UTC, awais-ansari commented on src/index.scss
> +}
We can ignore these classes and add the closest paragon classes.

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +            <span className={classNames({ 'margin-left-7px': channel === 'push' })}>
We can ignore push case for now.

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +
It can be refactored.

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +                        name="email_cadence"
it should be the dynamic name.

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +                    Daily
Translation is missing

2024-03-18 19:39 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +                      marginTop: '-0.8rem',
adding class for this and try to avoid - margin.

2024-03-19 07:04 UTC, ayesha-waris commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +                    Daily
It will be made dynamic once BE PR is finalized

2024-03-19 07:04 UTC, ayesha-waris commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +                        name="email_cadence"
It will be made dynamic once BE PR is finalized

2024-03-25 11:53 UTC, awais-ansari approved these changes

2024-03-25 15:46 UTC, ayesha-waris commented on src/index.scss
> +
Adding this class is intentional because padding needs to be adjusted  dynamically  based on specific conditions. As Paragon classes have higher specificity in CSS, using px-4.5 does not let padding override by pr-0.
```
'd-flex align-items-center justify-content-center mb-2 h-4.5 column-padding',
  {
    'pr-0': channel === 'email',
    'pl-0': channel === 'web' && mobileView,
  }
```

2024-03-25 15:52 UTC, merged