fix: long email field on account page
openedx/frontend-app-account pull request #1024
Opened 2024-04-02 10:37 UTC by bydawen

Fix for the long email field to prevent page break for the mobile view:

If user has a long type email it will be overlap from content of page:
<img width="504" alt="1" src="https://github.com/openedx/frontend-app-account/assets/25877054/446e285c-2d19-4670-a4bd-85b15bbfc107">

After fix:
<img width="536" alt="2" src="https://github.com/openedx/frontend-app-account/assets/25877054/a9d02fb6-8b1e-4e60-91ec-57df03af042c">

2024-04-02 10:37 UTC, openedx-webhooks commented
Thanks for the pull request, @bydawen! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-04-05 14:50 UTC, e0d commented
@bydawen I've invited you the triage team which will allow tests to run automatically in the future, please accept that invite when you receive it.

2024-04-05 15:14 UTC, mphilbrick211 commented
Hi @openedx/2u-aperture! This, along with its [backport](https://github.com/openedx/frontend-app-account/pull/1025), are ready for review.

2024-04-22 18:18 UTC, mphilbrick211 commented
Hi @hurtstotouchfire - can you confirm if Aperture will be maintaining this repo?

2024-05-01 19:23 UTC, mphilbrick211 commented
Hi @openedx/2u-vanguards! This is ready for review along with its [backport](https://github.com/openedx/frontend-app-account/pull/1025). Thanks!

2024-09-05 15:06 UTC, ihor-romaniuk commented
@mphilbrick211 @openedx/2u-vanguards It seems like it is ready for review and merge. Could we speed it up, please?

2024-09-06 01:16 UTC, mphilbrick211 commented
Hi @openedx/2u-vanguards - are you still maintaining this repo? If so, could you please give this a look? Thanks!

2024-10-24 21:27 UTC, mphilbrick211 commented
@openedx/2u-infinity flagging for you. Thanks!

2024-12-10 19:29 UTC, mphilbrick211 commented
> @openedx/2u-infinity flagging for you. Thanks!

Friendly ping, @openedx/2u-infinity!

2024-12-23 14:02 UTC, awais-ansari requested changes

2024-12-23 14:02 UTC, awais-ansari commented on src/account-settings/EmailField.jsx
> +            <p data-hj-suppress className="text-truncate">{renderValue()}</p>
In my opinion, it's not a good idea to truncate the email. If you want to truncate it, you should add a tooltip to view the full email address.

2025-02-12 22:09 UTC, mphilbrick211 commented
Hi @ihor-romaniuk and @awais-ansari! Just checking to see if this is still in progress?

2025-03-03 12:27 UTC, ihor-romaniuk commented
@mphilbrick211 Yes, it still in progress. We are working on it.

2025-03-30 21:32 UTC, Lunyachek commented
Hello everyone! I'll continue working on this PR.

I've added a tooltip to the email field. After the initial implementation, I noticed that the tooltip didn't look good - it appeared in the center of the email field row (you can see it in the screenshot below). So I decided to hide the tooltip on desktop resolutions and show it only on mobile.

<img width="1840" alt="Снимок экрана 2025-03-31 в 00 17 57" src="https://github.com/user-attachments/assets/973ecead-2d02-478a-bf43-8172db641f03" />

Another minor CSS change is related to the case where we have additional text like Pending confirmation. I decided to place it entirely on the next line for better readability.

<img width="1796" alt="Снимок экрана 2025-03-31 в 00 16 28" src="https://github.com/user-attachments/assets/4668dc2a-049d-4c46-9597-1e06ac2b7ac4" />

<img width="1840" alt="Снимок экрана 2025-03-31 в 00 31 49" src="https://github.com/user-attachments/assets/46c0d84b-221e-4de8-ae6d-42f47de6a1bd" />

2025-07-07 15:45 UTC, bydawen commented
@mphilbrick211 Hi) Can you help with the review here please? Thank you in advance!

2025-07-16 18:54 UTC, mphilbrick211 commented
@openedx/2u-infinity hi there! Checking to see if anyone can please take a look at this? Thanks!

2025-07-22 09:02 UTC, open-craft-grove commented
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10767666572.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10767666572-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10767666572-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10767666572-tutor-requirements.txt)

2025-07-22 09:59 UTC, open-craft-grove commented
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10768039323.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10768039323-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10768039323-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10768039323-tutor-requirements.txt)

2025-08-08 13:13 UTC, awais-ansari approved these changes

2025-08-08 13:25 UTC, open-craft-grove commented
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10961775292.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10961775292-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10961775292-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1024-f47ce0-51564656-10961775292-tutor-requirements.txt)

2025-08-18 09:35 UTC, ihor-romaniuk approved these changes

2025-08-28 10:07 UTC, merged