feat: implented notification preference UI for cadence
openedx/frontend-app-account pull request #1033
Opened 2024-04-15 15:34 UTC by ayesha-waris

[INF-1227](https://2u-internal.atlassian.net/browse/INF-1277)
[INF-1360](https://2u-internal.atlassian.net/browse/INF-1360)
Description:

We now will have a new email setting related to email cadences.
Options for email cadence for a notification can be Daily, Weekly and Immediately.
Complete UI as shown in [mockup](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=2072-8529&mode=design&t=2oADgBEXGpGyVx5L-0)

Uploading Screenshot 2024-03-14 at 2.00.43 PM.png…

Complete integration with BE to successfully update these email cadence settings

2024-04-15 22:33 UTC, awais-ansari approved these changes

2024-04-16 10:44 UTC, sundasnoreen12 commented on src/index.scss
> +    font-weight: 700;
we have paragon class "**font-weight-bold**" for font-weight 700

2024-04-16 10:44 UTC, sundasnoreen12 commented on src/index.scss
> +.margin-left-2{
add space before curly bracket 
also add space on L#96

2024-04-16 10:44 UTC, sundasnoreen12 commented on src/index.scss
> +    font-weight: 700;
we have paragon class "**font-weight-bold**" for font-weight 700

2024-04-16 10:47 UTC, sundasnoreen12 commented on src/index.scss
> +    padding-right: 32px;
use paragon classes
instead of padding-left: 32px; use pl-4.5
instead of padding-right: 32px; use pr-4.5

2024-04-16 10:48 UTC, sundasnoreen12 commented on src/index.scss
> +  .font-size-14{
add space before curly bracket here and L#36

2024-04-16 11:11 UTC, sundasnoreen12 requested changes
just 2 small changes

2024-04-16 17:53 UTC, sundasnoreen12 approved these changes

2024-05-07 11:54 UTC, merged