fix: fixed hover color of cadence button
openedx/frontend-app-account pull request #1043
Opened 2024-05-08 19:38 UTC by ayesha-waris

[INF-1227](https://2u-internal.atlassian.net/browse/INF-1277)
[INF-1360](https://2u-internal.atlassian.net/browse/INF-1360)

- fixed hover colors of email cadence button
- added environment variable for email channel

We now will have a new email setting related to email cadences.
Options for email cadence for a notification can be Daily, Weekly, Immediately and never.
Complete UI as shown in [mockup](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=2072-8529&mode=design&t=2oADgBEXGpGyVx5L-0)

2024-05-09 06:03 UTC, muhammadadeeltajamul approved these changes
nit: In `src/index.jsx`, default value for `SHOW_EMAIL_CHANNEL` is of type `boolean` whereas the value of the same environment variable in `.env` file is `string` type. It is better to use same datatype for default value (in this case `boolean`)

2024-05-09 07:16 UTC, sundasnoreen12 requested changes

2024-05-09 07:16 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceColumn.jsx
> +import { getConfig } from '@edx/frontend-platform';
place this import statement to its related group

2024-05-09 07:16 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceColumn.jsx
> +  return ((showEmailChannel === 'true' || channel === 'web') && (
if we have more then 2 channels and showEmailChannel is false then this block will not execute for other channels, i think we need to update this check try below condition instead of web . 
channel !='email'

2024-05-09 07:16 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceColumn.jsx
> +  <div className={classNames('d-flex flex-column', { 'border-right': channel !== 'email' && showEmailChannel === 'true' })}>
i think the border will be  on the left side if we have more than 1 channels. try and check its behavior. 
above will not work as expected if we will have more than 2 channels

2024-05-09 14:18 UTC, awais-ansari requested changes

2024-05-09 14:18 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceColumn.jsx
> +  return ((showEmailChannel === 'true' || channel === 'web') && (
`flag || (channel !== "email" && !flag)` This condition will render all the channels regardless of the flag and only render the email channel when the flag is true.

Please move this logic into a helper function.

2024-05-10 12:36 UTC, awais-ansari requested changes

2024-05-10 12:36 UTC, awais-ansari commented on src/notification-preferences/data/constants.js
> +  : { WEB: 'web' };
Create a util function for this.

2024-05-13 09:14 UTC, sundasnoreen12 requested changes

2024-05-13 12:58 UTC, sundasnoreen12 approved these changes

2024-05-14 07:47 UTC, awais-ansari approved these changes

2024-05-14 07:47 UTC, awais-ansari commented on src/index.scss
> +    background-color: #F2F0EF !important;
Please use a paragon token instead of a hard-coded color code. like $light-300 == #F2F0EF

2024-05-14 11:12 UTC, merged