feat: removed app level toggles
openedx/frontend-app-account pull request #1062
Opened 2024-06-12 08:03 UTC by sundasnoreen12

[INF-1415](https://2u-internal.atlassian.net/browse/INF-1415)

**Description**
Remove app level toggles from preferences UI in accounts MFE

ACs

1. App-level toggles from preferences UI in accounts MFEn should be removed. 
2. Remove Type form each app and move it to top
3. Remove dividers between app
4. Rename core notifications in discussions to Activity notifications
5. Enable core notification toggle that is disabled by default

**Screenshot**
<img width="885" alt="Screenshot 2024-06-12 at 12 54 31 AM" src="https://github.com/openedx/frontend-app-account/assets/72802712/4b087210-fa36-49ed-bded-8de282ca2d16">

2024-06-13 15:07 UTC, awais-ansari requested changes

2024-06-13 15:07 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +import { selectPreferenceAppToggleValue, selectSelectedCourseId, selectPreferencesOfApp } from './data/selectors';
rename `selectPreferencesOfApp` to `selectAppPreferences`

2024-06-14 09:12 UTC, awais-ansari approved these changes

2024-06-14 09:48 UTC, ayesha-waris approved these changes

2024-06-14 10:07 UTC, merged