feat: Added PluginSlot to wrap IDVerificationPage component
openedx/frontend-app-account pull request #1097
Opened 2024-08-09 14:22 UTC by rijuma

### Description

This wraps the IDVerificationPage with a `PluginSlot` component to allow experiment with a new IDV flow.

#### How Has This Been Tested?

Tested on local environment and the default behavior is shown as expected.

#### Merge Checklist
* [x] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2024-08-12 12:46 UTC, schenedx requested changes
See my inline comment.

2024-08-12 12:46 UTC, schenedx commented on src/index.jsx
> -          <Route path="/id-verification/*" element={<IdVerificationPage />} />
With a change like this, if we deploy this to production, the existing IDV flow will be gone. 
I think we need a period of this code where the plugin slot and the existing IDV flow co-exist for a while. This way, while we build out the plugin slot, the existing IDV flow still serves our learners.
Then we need a waffle flag to do the switch from the entry link, which is probably 3 different places.

2024-08-12 13:24 UTC, MichaelRoytman reviewed
This looks good to me. I know you wanted to discuss more today, so I've held off on approving for now.

Also, should/can we test the use of the `PluginSlot` on the page?

2024-08-12 13:24 UTC, MichaelRoytman commented on src/index.jsx
> -          <Route path="/id-verification/*" element={<IdVerificationPage />} />
Whatever component is wrapped by the `PluginSlot` (i.e. `IdVerificationPage`) is the "default component" and will be rendered by default if there is no plugin configuration specified (e.g. in an `env.config.[js|jsx]` file in `edx-internal`) or no overriding plugin in the said plugin configuration, so this deployment strategy isn't necessary. If we merge this as-is, there will be no changes to the IDV page in the learning MFE for 2U or any other deployments. There are more details the [frontend-plugin-framework docs](https://github.com/openedx/frontend-plugin-framework/?tab=readme-ov-file#default-content). Does that assuage your concerns?

2024-08-12 13:53 UTC, rijuma commented on src/index.jsx
> -          <Route path="/id-verification/*" element={<IdVerificationPage />} />
Indeed. I tested it locally but with no configuration and the `<IdVerificationPage>` is rendered by default.

2024-08-12 13:54 UTC, rijuma commented
> This looks good to me. I know you wanted to discuss more today, so I've held off on approving for now.
> 
> Also, should/can we test the use of the `PluginSlot` on the page?

I tested it and the behavior is exactly the same. We could test whatever you have in mind.

2024-08-12 14:08 UTC, MichaelRoytman commented
Is it necessary to write a test for the application to ensure that the `PluginSlot` is rendered (e.g something like [this](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/courseware/course/sequence/Unit/UnitSuspense.test.jsx#L82))?

2024-08-12 14:37 UTC, schenedx commented on src/index.jsx
> -          <Route path="/id-verification/*" element={<IdVerificationPage />} />
Nice. I didn't know plugin slot handles this the way it should be. Thank you for pointing it out.

2024-08-12 14:37 UTC, schenedx approved these changes
👍

2024-08-13 13:18 UTC, rijuma commented
> Is it necessary to write a test for the application to ensure that the `PluginSlot` is rendered (e.g something like [this](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/courseware/course/sequence/Unit/UnitSuspense.test.jsx#L82))?

We discussed this offline and we came to the conclusion that adding a test for the index file would be complicated enough to consider it out of scope for this small update.

2024-08-14 13:40 UTC, MaxFrank13 commented
Hello 👋  I just have one recommendation/request to document the plugin slot using [this format](https://github.com/openedx/frontend-app-account/tree/master/src/plugin-slots) in the MFE. You can use frontend-app-learning for reference as well — [PluginSlots documentation](https://github.com/openedx/frontend-app-learning/tree/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/plugin-slots) & [PluginSlot being implemented ](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/courseware/course/sequence/Sequence.jsx#L213)

2024-08-14 17:40 UTC, jsnwesson commented
Hey all! Agreeing with Max that it would be nice to have a place where all PluginSlots live. You can reference [the Learning MFE](https://github.com/openedx/frontend-app-learning/tree/master/src/plugin-slots) to see how they organize three PluginSlots. This will also make testing a PluginSlot much easier, I think.

2024-08-16 13:22 UTC, MaxFrank13 approved these changes

2024-08-16 13:27 UTC, merged