Paragon form component deprecations
openedx/frontend-app-account pull request #612
Opened 2022-07-19 09:31 UTC by abdullahwaheed

### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102#)

### What has changed
Updated deprecated `ValidationFormGroup` to `Form.Group`, `Input` to `Form.Control` and `Checkbox` to `Form. CheckBox` and updated respective unit tests
Created a separate `EditableSelectField` for selections as `EditableField` would become much conditional.

2022-08-11 12:25 UTC, davidjoy requested changes
One small-ish factoring change... I also want to pull the branch down and test it.  Were you able to visually verify all these changes worked?  I know some of these UIs are hard to find.

2022-08-11 12:25 UTC, davidjoy commented on src/account-settings/EditableSelectField.jsx
> +  if (getConfig().ENABLE_COPPA_COMPLIANCE && name === 'level_of_education' && options) {
Hm, because this conditional is specific to level_of_education, it'd be good to extract it from `EditableSelectField` and modify the `options` as they're passed into the component via props.  That way there's an obvious filtering of options for `level_of_education` where it's being used, rather than quietly changing it within this component where someone might not expect that to happen.

2022-08-12 06:52 UTC, abdullahwaheed commented
> One small-ish factoring change... I also want to pull the branch down and test it. Were you able to visually verify all these changes worked? I know some of these UIs are hard to find.

Yes I have tested these changes. Let me share screenshots of changes with PR

2022-08-17 17:44 UTC, davidjoy approved these changes

2022-11-07 08:27 UTC, BilalQamar95 approved these changes

2022-11-08 11:45 UTC, ishahroz approved these changes

2022-11-08 13:42 UTC, merged