build: fix peer depends and update common depends
openedx/frontend-app-account pull request #615
Opened 2022-07-31 08:22 UTC by ghassanmas

fix peer depends and update common depends

2022-07-31 08:22 UTC, openedx-webhooks commented
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-08-02 14:25 UTC, natabene commented
@ghassanmas Thank you for your contribution, I kicked off the checks.

2022-08-02 17:13 UTC, ghassanmas commented
@natabene Tests should be resolved now I have run them on the fork. Also apply for other PRs in profile and gradebook

2022-08-04 21:55 UTC, timmc-edx commented
@davidjoy Would you be able to review this one, or point me to who should?

2022-08-09 15:32 UTC, davidjoy commented on package.json
> -    "@tensorflow/tfjs-converter": "1.7.4",
This bumps these tensorflow libs through two major versions - do we know that we've absorbed the breaking changes in them and that this won't break?

2022-08-09 15:34 UTC, davidjoy requested changes
One change request and one sanity check on some of the version bumps.

2022-08-09 16:51 UTC, ghassanmas commented on package.json
> -    "@tensorflow/tfjs-converter": "1.7.4",
This patch more or less a backport of https://github.com/openedx/frontend-app-account/commit/0527c735295949c71074021b07530d2c70e38cb0  and more of discussion can be found https://github.com/openedx/frontend-app-account/pull/611

2022-08-09 17:02 UTC, ghassanmas commented on package.json
> +    "peerDependencies": {
Anyway if you checkout to fronted-app-learning amd run `npm ls boostrap` you should get 4.6.1.

2022-08-09 17:18 UTC, ghassanmas commented on package.json
> -    "@tensorflow/tfjs-converter": "1.7.4",
These are not really used directly, I have researched the code and they are just there as peer depends of `@tensorflow-models/blazeface 0.0.7` which require those exact versions [hence](https://github.com/tensorflow/tfjs-models/blob/84a4d132f120bcb24cfbc2b16ede7956e5ea9588/blazeface/package.json#L16-L17). That being said, if something would break it would more likely to have broken before.

2022-09-02 15:03 UTC, davidjoy commented on package.json
> +    "peerDependencies": {
MFEs can't have peerDependencies - they're not a package that gets installed as a dependency.  I don't know if somehow adding peerDependencies removes a warning or something, but I don't think that's the right way to solve whatever problem we're seeing.

It should not matter if MFEs have consistent versions of paragon - the code isn't shared anyway, I don't think it's meaningful to optimize for a consistent version.  We shouldn't limit an MFEs version of a library because a different, independent MFE is at a particular version, that's not how the system was designed/intended to be used.  

If we need to update these dependencies for nutmeg for some reason, we should just update them to latest - artificially pinning them at earlier versions is only going to cause problems and confusion later.

2022-09-06 14:36 UTC, ghassanmas commented on package.json
> +    "peerDependencies": {
> MFEs can't have peerDependencies - they're not a package that gets installed as a dependency. I don't know if somehow adding peerDependencies removes a warning or something, but I don't think that's the right way to solve whatever problem we're seeing.


The end goal is to force to use a spesfic verion of bootsrap, and I force to do so because otherwise it would break the build. I think it would be doable to have the same result if I instead moved it to deps instead of creating per depnds. 

>  It should not matter if MFEs have consistent versions of paragon - the code isn't shared anyway, I don't think it's meaningful to optimize for a consistent version. We shouldn't limit an MFEs version of a library because a different, independent MFE is at a particular version, that's not how the system was designed/intended to be used.

Again the pinned vresion would resolve the failed build because the artificial created version of boostrap after updarading paragon will result in failed build. When I was debuggin this, I was confused, such that why the paragon update made the build to fail while the same version is being in learning and it builds okay. This made me further debugging the depends of paragon between the learning and other MFEs what I found is that boostrap version is different in the learning thus I tried pin  boostrap version, rebuild again and the result was ok. 

>  If we need to update these dependencies for nutmeg for some reason, we should just update them to latest - artificially pinning them at earlier versions is only going to cause problems and confusion later.

I agree that the right path would be frequently update depends for each MFE (Note: I am referring to the open release branches). The thing is its hard to know which version suppose to be compitable with open-release, so my stratgey is find the maximum version of all MFEs and consider that the right version.

Add to that for paragon for example the version is already pinned so artificially updaing the depends is not possible, a different startgey would be to go check the change-log of paragon version 19.* and find if there is any breaking changes and if not, then use the last minor version of paragon 19. which in this case is [19.25.3](https://github.com/openedx/paragon/releases/tag/v19.25.3)

So in summary; _Assuming using paragon 19.25.3 wouldn't require us to pin boostrap and assuming MFEs would work as epxected using that version_. Would you accept such change? (To MFEs nutmeg branch, learning, account profile and gradebook)

2022-09-06 16:40 UTC, ghassanmas commented on package.json
> +    "peerDependencies": {
@davidjoy even using the latest minor version of paragon 19 didn't resolve it. 
Anyway I stumbled upon this issue while checking paragon openedx/paragon/pull/1562 it seems the way to resolve to include the new varriable of bootsrap and if an MFE is using older paragon the solution was to pin it just as I did here [ref commit in paryment mfe](https://github.com/openedx/frontend-app-payment/commit/cab00beedc3ee6a8cf5fe809d04ede30456c6d42) The difference is that they don't add it per rather direclty in depends. 

However I went over npm docs, and the right way to do is to define [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) 
I am now testing with overrides and see if build would  success and then I willl deploy the same version in production to see if it would also would as expected

2022-09-06 16:56 UTC, ghassanmas commented on package.json
> +    "peerDependencies": {
I tested and worked as expcted. 
To test in production you can go: [https://apps.edx.gsgapp.io/account](https://apps.edx.gsgapp.io/account)  you can use admin@zaat.dev and "zaatdev" as pass.

2022-10-05 06:57 UTC, abdullahwaheed commented
@ghassanmas there are some snapshots failing and local development server is not working with following error:
```
> @edx/frontend-app-account@1.0.0-semantically-released start
> fedx-scripts webpack-dev-server --progress

Running with resolved config:
/.../frontend-app-account/node_modules/@edx/frontend-build/config/webpack.dev.config.js

No local module configuration file found. This is fine.
1% setup initialize[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (.../frontend-app-account/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Command.<anonymous> (.../frontend-app-account/node_modules/webpack-cli/lib/webpack-cli.js:1672:7)

```

 Please pull latest code from master, this error is due to old version of webpack, which is being updated in frontend-build.

2022-10-12 07:21 UTC, ghassanmas commented
@abdullahwaheed just pushed a fix, by overrideing webpack-cli version hence webpack/webpack/issues/15951 . Also note this error already exists in nutmeg.master.

2022-10-12 07:36 UTC, ghassanmas commented
Secondaly for the tests I have backported 0527c735295949c71074021b07530d2c70e38cb0 and seems to resolve the failing tests

2022-10-13 10:17 UTC, BilalQamar95 commented
@ghassanmas Are we sure that `useEffect` dependencies update won't cause unnecessary renders? If this was just to satisfy the linter I'd probably revert this and leave it as-is, ignoring the rule in case of `useEffect` Hook.

2022-10-13 10:54 UTC, ghassanmas commented
> @ghassanmas Are we sure that `useEffect` dependencies update won't cause unnecessary renders? If this was just to satisfy the linter I'd probably revert this and leave it as-is, ignoring the rule in case of `useEffect` Hook.

That chagne is backported to from https://github.com/openedx/frontend-app-account/commit/0527c735295949c71074021b07530d2c70e38cb0 to fix the failed tests.

2022-10-31 14:49 UTC, arbrandes commented
Reviewers, how are we feeling about this?  Any further changes requested?  (@davidjoy, do you want to hand off final say to somebody else?  Who owns the Account MFE, these days?)

2022-10-31 14:50 UTC, arbrandes commented
Also, @ghassanmas, do you mind commenting on https://github.com/openedx/frontend-wg/issues/140 so I can assign it to you?  Or maybe you can assign yourself, not sure. :)

2022-11-01 13:23 UTC, ghassanmas commented
@arbrandes I don't I can, but I have just comment there my perspective/finding  on that.

2023-01-26 23:31 UTC, mphilbrick211 commented
Hi @arbrandes and @ghassanmas! Just checking to see if this is still being pursued? If so, can it be reviewed/merged?

2023-02-07 20:46 UTC, mphilbrick211 commented
@ghassanmas @arbrandes friendly ping on this :)

2023-02-08 12:43 UTC, ghassanmas commented
@mphilbrick211 I think it's fine to close it, since I don't think we support nutmeg releases anymore.

2023-02-08 20:51 UTC, mphilbrick211 commented
Ok, closing!

2023-02-08 20:51 UTC, closed without merging

2023-02-08 20:52 UTC, openedx-webhooks commented
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/615&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-07-31+08:22&entry.1917517419=2023-02-08+20:51&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->