Revert "Upgraded frontend-build version to v12"
openedx/frontend-app-account pull request #624
Opened 2022-08-18 20:35 UTC by alangsto

Reverts openedx/frontend-app-account#613

This PR is causing edits to form fields on the account settings page to error:

<img width="631" alt="Screen Shot 2022-08-18 at 4 29 32 PM (1)" src="https://user-images.githubusercontent.com/46360176/185489499-05ddc46b-c749-40b4-9698-41c2d1f68145.png">

Reverting because we would like to release a form for COPPA compliance, but we are blocked from deploying to prod by the errors from this PR.

2022-08-18 20:36 UTC, alangsto commented
fyi @BilalQamar95

2022-08-18 21:06 UTC, ashultz0 approved these changes

2022-08-19 06:46 UTC, abdullahwaheed commented
@alangsto `ValidationFormGroup` is removed in #612 and i have tested is locally. I think we should merge it and this issue will automatically resolve
![image](https://user-images.githubusercontent.com/42172960/185558763-3123b05d-c0b5-405f-b7e8-3c230681d1bb.png)

2022-08-19 10:41 UTC, schenedx requested changes
This is a huge PR to revert.
I am wondering if we can fix forward.
Do we know the root cause of the bug where the edit name button leads directly to error view?

2022-08-19 12:39 UTC, closed without merging