Feature: Persian language Support
openedx/frontend-app-account pull request #666
Opened 2022-10-17 05:40 UTC by CodeWithEmad

Feature: Persian language Support

Hello everyone
I'm glad to announce that we translated all openedx components in transifex to Persian and fa_IR is 100% translated and 100% reviewed.

in this PR, I've added:
new translations to `i18n/messages/fa_IR.json`,
`fa-ir` in messages in `src/i18n/index.js`,
`fa-ir` code in constants.js in `src/account-settings/site-language`,
and `fa_IR` code in transifex_langs variable in `Makefile`.

is there anything else I should do?

2022-10-17 05:40 UTC, openedx-webhooks commented
Thanks for the pull request, @CodeWithEmad!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-12-29 05:41 UTC, ishahroz requested changes
Looks good to me. Kindly resolve the sync conflicts before we can merge.

2023-01-11 22:29 UTC, mphilbrick211 commented
Hi @CodeWithEmad! Just following-up on this pull request. Looks like changes have been requested and branch conflicts need to be resolved. Please let us know if you plan to pursue this PR. Thanks!

2023-01-12 12:45 UTC, CodeWithEmad commented
Hi @mphilbrick211
all conflicts resolved

2023-01-13 12:52 UTC, ishahroz approved these changes
Looks good to me.

2023-01-18 13:07 UTC, ishahroz requested changes

2023-01-18 13:07 UTC, ishahroz commented on src/account-settings/site-language/constants.js
> +    {
@CodeWithEmad Linting is failing here because expected indentation is of 2 spaces but found 4. Kindly resolve, so we can merge.

2023-01-18 16:11 UTC, CodeWithEmad commented on src/account-settings/site-language/constants.js
> +    {
sure, done.

2023-01-26 21:14 UTC, e0d commented on src/account-settings/site-language/constants.js
> +    {
@ishahroz if this looks good to you now, can you merge?

2023-01-27 17:41 UTC, mphilbrick211 commented
Hi @CodeWithEmad! Just flagging for you that tests have run, but changes have been requested.

2023-01-28 11:05 UTC, CodeWithEmad commented
@mphilbrick211 I fixed the linting issue, last week. @ishahroz might forgot to approve the requested changes.

2023-01-30 22:35 UTC, mphilbrick211 commented
Thanks, @CodeWithEmad! @ishahroz would you mind taking a look? Thank you!

2023-02-01 05:59 UTC, abdullahwaheed approved these changes

2023-02-01 06:33 UTC, ishahroz approved these changes

2023-02-01 06:36 UTC, merged

2023-02-01 06:36 UTC, openedx-webhooks commented
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/666&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2022-10-17+05:40&entry.1917517419=2023-02-01+06:36&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->