feat: added notification preference ui
openedx/frontend-app-account pull request #784
Opened 2023-05-04 06:31 UTC by muhammadadeeltajamul

Added Notification Preferences UI components.

- JumpNav component will have a new option
- Created new page that will all the active courses in which user is enrolled in
- When a user will select a course, he/she will be redirected to preferences page of the selected course  

This is a draft PR. A lot of changes will be made when integrating required API's and adding test cases.

2023-05-09 06:20 UTC, sundasnoreen12 requested changes

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +/* eslint-disable no-unused-vars */
remove eslint-disable line

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +// import { getAuthenticatedHttpClient } from '@edx/frontend-platform/auth';
remove commented code if they are of no use

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +  // const { data } = await getAuthenticatedHttpClient().get(url);
remove commented code if they are of no use

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +    { id: 'course-v1:edX+Happiness+At+Work_Course', name: 'The Foundation of Happiness At Work' },
title issue replace with "The Foundations of Happiness at Work"

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +    { id: 'course-v1:edX+Empathy+At+Work_Course', name: 'Empathy and Emotional Intelligence At Work' },
title issue kindly replace with "Empathy and Emotional Intelligence at Work"

2023-05-09 06:20 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationCourses.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
remove eslint disable line

2023-05-09 06:27 UTC, muhammadadeeltajamul commented on src/notification-preferences/data/service.js
> +    { id: 'course-v1:edX+Happiness+At+Work_Course', name: 'The Foundation of Happiness At Work' },
this is a dummy data... it will be removed when integrating api's.

2023-05-09 06:28 UTC, muhammadadeeltajamul commented on src/notification-preferences/data/service.js
> +    { id: 'course-v1:edX+Empathy+At+Work_Course', name: 'Empathy and Emotional Intelligence At Work' },
Same. This is also dummy data...

2023-05-09 06:29 UTC, muhammadadeeltajamul commented on src/notification-preferences/data/service.js
> +// import { getAuthenticatedHttpClient } from '@edx/frontend-platform/auth';
These are required imports that will be added when integrating API's.

2023-05-09 06:30 UTC, muhammadadeeltajamul commented on src/notification-preferences/data/service.js
> +  // const { data } = await getAuthenticatedHttpClient().get(url);
This is API call for it that will bring data whose structure will be same as dummy data. It will be removed when integrating API's

2023-05-09 06:31 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationCourses.jsx
> +            </Link>
Added

2023-05-09 06:41 UTC, muhammadadeeltajamul commented on src/notification-preferences/data/service.js
> +/* eslint-disable no-unused-vars */
It will also be removed when integrating API's

2023-05-09 06:53 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationCourses.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Normally I don't add dispatch to dependency array since it doesn't change but added here

2023-05-09 06:54 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +        <div className="mt-3 pb-5.5">
Updated

2023-05-09 06:55 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferences.jsx
> +    <div className="ml-auto mr-auto" style={{ width: '828px' }}>
Added class

2023-05-09 06:55 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferences.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
The dependencies it requires will cause few extra re-renders. So disabling lint for this line is better.

2023-05-09 09:55 UTC, awais-ansari requested changes

2023-05-09 09:55 UTC, awais-ansari commented on src/index.scss
> +}
using responsive class from paragon.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationCourses.jsx
> +  }, [courseStatus, dispatch]);
this condition will not fetch the course again if the API call fails the first time and the user come back to this page again. update it. like
useEffect(() => {
    if (courseStatus === IDLE_STATUS || courseList.length === 0) {
      dispatch(fetchCourseList());
    }
  }, [courseStatus, dispatch]);

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationCourses.jsx
> +    <div className="ml-auto mr-auto w-828px">
used container wrapper from paragon

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +  }, [courseId, course, preferences]);
course, preferences are extra dependencies here. you can remove it.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +  }
Add spinner if API call is in progress.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +    <div className="ml-auto mr-auto w-828px">
use container from paragon

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +        }
memoize the preferences list.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +            <NotificationPreferenceGroup groupKey={key} />
add key param for rendering.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +const NotificationPreferenceGroup = ({ intl, groupKey }) => {
change from groupKey to groupId.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  useEffect(() => {}, [courseId]);
remove it. courseId will re-render this course.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  };
memoize this function as it is passing to child component.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +export default injectIntl(NotificationPreferenceGroup);
use React.memo to memoize this component as it is a nested child component. it will render on every parent re-render.

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +            ))
create memoize list and also add key param. change groupKey to groupId

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +export default injectIntl(NotificationPreferenceRow);
memoize this component

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +  };
memoize this callback

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +      <span className="w-66">
use col class from paragon

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/ToggleSwitch.jsx
> +export default ToggleSwitch;
memoize this component

2023-05-09 09:55 UTC, awais-ansari commented on src/notification-preferences/data/selectors.js
> +);
change element to course. 
call getCourseList selector instead of `state.notificationPreferences.courses.courses`

2023-05-13 20:13 UTC, sundasnoreen12 requested changes

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationCourses.jsx
> +  }
you can memo this like
 
const SpinnerComp = useMemo(() => {
  if (courseStatus === LOADING_STATUS) {
    return (
     <div className="d-flex h-100">
        <Spinner
          variant="primary"
          animation="border"
          className="mx-auto my-auto"
          style={{ width: '4rem', height: '4rem' }}
        />
      </div>
    );
  }
  return null;
}, [courseStatus]);
if (SpinnerComp) { return SpinnerComp; }

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationCourses.jsx
> +export default injectIntl(NotificationCourses);
memo this
export default injectIntl(React.memo(NotificationCourses));

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  }, [groupId]);
add courseId in the dependency array

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +  }, [dispatch, groupId, preferenceName]);
no need to pass dispatch here, instead pass updatePreferenceValue

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferences.jsx
> +  }
you can memo this like

const SpinnerComp = useMemo(() => {
    if (notificationStatus === LOADING_STATUS) {
        return (
              <div className="d-flex h-100">
                      <Spinner
                        variant="primary"
                        animation="border"
                        className="mx-auto my-auto"
                        style={{ width: '4rem', height: '4rem' }}
                      />
              </div>
        );
    }
  return null;
}, [notificationStatus]);
if (SpinnerComp) { return SpinnerComp; }

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferences.jsx
> +export default NotificationPreferences;
memo this component
export default React.memo(NotificationPreferences);

2023-05-13 20:13 UTC, sundasnoreen12 commented on src/notification-preferences/ToggleSwitch.jsx
> +  <Form.Switch checked={value} onChange={(event) => onChange(event.target.checked)} />
add callback function for onChange

2023-05-15 01:12 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationCourses.jsx
> +export default injectIntl(NotificationCourses);
NotificationCourses component is not taking any props (except intl). I don't think that React.memo will be helpful

2023-05-15 01:14 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferences.jsx
> +export default NotificationPreferences;
NotificationPreferences component has no props. React.memo will not be of any use

2023-05-15 01:15 UTC, muhammadadeeltajamul commented on src/notification-preferences/ToggleSwitch.jsx
> +  <Form.Switch checked={value} onChange={(event) => onChange(event.target.checked)} />
onChange is being passed as prop from NotificationPreferenceGroup and from NotificationPreferenceRow. These calls have been wrapped in useCallback there

2023-05-15 01:20 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +  }, [dispatch, groupId, preferenceName]);
updatePreferenceValue is a function. I don't think we need to pass function in dependency list. Added dispatch to avoid disabling lint for this line

2023-05-16 11:41 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationCourses.jsx
> +  }
Since this component is not being rendered multiple times, hence memoization is not required. Excessive memoization should be avoided in code

2023-05-16 11:41 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferences.jsx
> +  }
Memoization not required here

2023-05-16 12:23 UTC, muhammadadeeltajamul commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  }, [groupId]);
Page will refresh everytime the courseId will change. Adding courseId to dependency array will have no effect

2023-05-16 12:46 UTC, sundasnoreen12 approved these changes

2023-05-18 12:23 UTC, awais-ansari requested changes

2023-05-18 12:23 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  }
please update the order. hooks should be called on top of function calls. Also, need to add a newline between the two functions or start new logic.

2023-05-18 12:23 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceGroup.jsx
> +  }, [groupId]);
this refer to this comment
`updatePreferenceValue is a function. I don't think we need to pass function in dependency list. Added dispatch to avoid disabling lint for this line`

Please follow the consistent practice in every component.

2023-05-18 12:23 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferences.jsx
> +    if (courseStatus !== SUCCESS_STATUS) {
Please add newline between logics

2023-05-19 11:56 UTC, awais-ansari approved these changes

2023-05-22 01:17 UTC, merged