feat: integrate notification preferences api
openedx/frontend-app-account pull request #794
Opened 2023-05-26 10:54 UTC by muhammadadeeltajamul

Integrated Notification Preferences API

Ticket: [INF-892](https://2u-internal.atlassian.net/browse/INF-892)

2023-05-31 14:10 UTC, awais-ansari requested changes
1. change group prefix to app prefix
2. change the attribute to a name or relevant field.

2023-06-01 07:37 UTC, sundasnoreen12 requested changes

2023-06-01 07:37 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferences.jsx
>      ))
preferenceGroupIds.map(groupId => (
  <NotificationPreferenceGroup groupId={groupId} key={group} />
))

2023-06-01 07:37 UTC, sundasnoreen12 commented on src/notification-preferences/data/selectors.js
> +export const selectPreferencesOfGroup = group => state => (
rename group into groupId for more clarity because its a groupId instead of holding whole group value.

2023-06-01 07:37 UTC, sundasnoreen12 commented on src/notification-preferences/data/selectors.js
> +export const selectSelectedCourse = () => state => (
update name into selectSelectedCourseId because it is returning selected course ID

2023-06-02 09:40 UTC, awais-ansari requested changes

2023-06-02 09:40 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceRow.jsx
> +            <OverlayTrigger
add id param

2023-06-05 05:22 UTC, sundasnoreen12 approved these changes

2023-06-05 14:20 UTC, awais-ansari approved these changes

2023-06-05 14:20 UTC, awais-ansari commented on src/notification-preferences/data/selectors.js
> +  state?.notificationPreferences.preferences.notEditable[appId]?.[name] || []
no need to add ? here `state?`

2023-06-06 06:04 UTC, merged