feat: make notification channel headings clickable in notification pr…
openedx/frontend-app-account pull request #981
Opened 2024-01-22 10:14 UTC by eemaanamir

[INF-1062](https://2u-internal.atlassian.net/browse/INF-1062)

### Explanation:

The code for the notification channel headings has been made more generic. An on-click event handler has been implemented along with relevant updates in the selectors, thunk, and service files needed for it. 

The implementation for the new API call can be found in [this PR](url).

2024-01-22 10:14 UTC, openedx-webhooks commented
Thanks for the pull request, @eemaanamir! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-01-22 12:53 UTC, awais-ansari requested changes

2024-01-22 12:53 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +                }
Please use conditional `formatMessage` object.

2024-01-22 12:53 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +                onClick={onColumnToggle}
nit: `onColumnToggle`  => `onChannelToggle`

2024-01-22 12:53 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +  );
This function can be refactored.

2024-01-22 12:53 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +                }
https://github.com/openedx/frontend-app-account/blob/master/src/notification-preferences/messages.js#L19

2024-01-22 12:53 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +              <NavItem
key prop is missing

2024-01-22 15:50 UTC, mphilbrick211 commented
Hi @eemaanamir! Thank you for this contribution. Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Thank you!

2024-01-23 08:16 UTC, sundasnoreen12 requested changes

2024-01-23 08:16 UTC, sundasnoreen12 commented on src/notification-preferences/data/selectors.js
> +export const selectPreferenceNonEditable = (appId) => state => (
rename it to **selectNonEditablePreferences** and remove braces around appId.

2024-01-23 08:16 UTC, sundasnoreen12 commented on src/notification-preferences/data/service.js
> +  });
move these into single line

2024-01-23 08:16 UTC, sundasnoreen12 commented on src/notification-preferences/data/thunks.js
> +  patchAppPreferenceToggle, patchChannelPreferenceToggle,
move **patchChannelPreferenceToggle** into next line.

2024-01-23 08:16 UTC, sundasnoreen12 commented on src/notification-preferences/data/thunks.js
> +) => (
move these into single line

2024-01-23 08:16 UTC, sundasnoreen12 commented on src/notification-preferences/data/thunks.js
> +      );
same as above

2024-01-23 14:02 UTC, awais-ansari requested changes

2024-01-23 17:56 UTC, sundasnoreen12 requested changes

2024-01-23 17:56 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +        && !isPreferenceNonEditable(preference));
use this
const activePreferences = appPreferences.filter(
    (preference) => preference[notificationChannel] && !isPreferenceNonEditable(preference)
  );

2024-01-24 10:44 UTC, awais-ansari requested changes

2024-01-24 10:44 UTC, awais-ansari commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +        || false;
I think we don’t need to explicitly define the `|| false` condition here. It can be more simplified.
const isPreferenceNonEditable = (preference) => nonEditable?.[preference.id]?.includes(notificationChannel)

2024-01-24 11:12 UTC, sundasnoreen12 requested changes

2024-01-24 11:12 UTC, sundasnoreen12 commented on src/notification-preferences/NotificationPreferenceApp.jsx
> +  }, [appId, appPreferences, courseId, dispatch, nonEditable]);
const onChannelToggle = useCallback((event) => {
    const { id: notificationChannel } = event.target;
    const isPreferenceNonEditable = (preference) => nonEditable?.[preference.id]?.includes(notificationChannel);

    const hasEditablePreferences = appPreferences.some(
        (preference) => preference[notificationChannel] && !isPreferenceNonEditable(preference),
    );

    dispatch(updateChannelPreferenceToggle(courseId, appId, notificationChannel, !hasEditablePreferences));
}, [appId, appPreferences, courseId, dispatch, nonEditable]);


We can modify the code by this way. Using some allows you to stop iterating through the array once a matching condition is found, potentially providing better performance than filter which iterates over the entire array.

2024-01-24 11:33 UTC, awais-ansari approved these changes

2024-01-24 12:35 UTC, sundasnoreen12 approved these changes

2024-01-24 16:20 UTC, mphilbrick211 commented
Hi @eemaanamir - have you had a chance to submit your [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base)? If so, the CLA check should turn green when you re-run the checks.

2024-01-25 11:01 UTC, closed without merging

2024-01-25 11:01 UTC, ayesha-waris commented
New PR created [INF-1062](https://github.com/openedx/frontend-app-account/pull/983)

2024-01-25 11:01 UTC, openedx-webhooks commented
@eemaanamir Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/981&entry.1484655318=https://github.com/eemaanamir&entry.752974735=2024-01-22+10:14&entry.1917517419=2024-01-25+11:01&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-01-25 11:01 UTC, openedx-webhooks commented
@eemaanamir Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/981&entry.1484655318=https://github.com/eemaanamir&entry.752974735=2024-01-22+10:14&entry.1917517419=2024-01-25+11:01&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-01-25 13:50 UTC, awais-ansari commented
I'm closing this PR because @eemaanamir CLS has been pending for a long time. Another team member created a new PR to unblock this change for merge.
New PR -> [983](https://github.com/openedx/frontend-app-account/pull/983)